---
- name: Ensure /etc/nodepool exists
  file:
    path: /etc/nodepool
    state: directory
  when: hostvars[inventory_hostname].nodepool is not defined
  become: true

- name: Ensure primary_node_private is localhost when not a nodepool node
  copy:
    content: 127.0.0.1
    dest: /etc/nodepool/primary_node_private
  when: hostvars[inventory_hostname].nodepool is not defined
  become: true

- name: Copy custom gate hooks into workspace
  template:
    src: custom_devstack_gate_hook
    dest: "{{ workspace }}/custom_devstack_gate_hook"

- name: Copy devstack gate to devstack gate safe
  copy:
    remote_src: true
    src: "{{ workspace }}/devstack-gate/devstack-vm-gate-wrap.sh"
    dest: "{{ workspace }}/safe-devstack-vm-gate-wrap.sh"
    mode: u=rwx,g=r,o=r

- name: Copy custom features.yaml into workspace
  copy:
    src: features.yaml
    dest: "{{ workspace }}/features.yaml"

- name: Output devstack gate env
  debug: msg="{{ devstack_gate_env }}"

- name: Ensure /opt/stack/logs doesnt exist from previous run
  file:
    state: absent
    path: "/opt/stack/logs/"
  become: true

- name: Create EOL branch patch file dir
  file:
    path: "{{ workspace }}/patches"
    state: directory
    mode: 0755
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups.all }}"
  when: "'mitaka' in override_zuul_branch"

- name: Copy EOL branch patch files
  copy:
    src: "{{ item[1] }}"
    dest: "{{ workspace }}/patches/"
  delegate_to: "{{ item[0] }}"
  with_nested:
    - "{{ groups.all }}"
    - [ "devstack_mitaka_providernet_pub_vlan.patch", "0001-Add-upper-constraint-for-setuptool-39-on-stable-newt.patch" ]
  when: "'mitaka' in override_zuul_branch"

- name: Copy playbook for patching centos
  copy:
    src: "fixup_centos_upperconstraints.yaml"
    dest: "{{ workspace }}/fixup_centos_upperconstraints.yaml"

- name: Run devstack gate
  environment: "{{ devstack_gate_env | combine(devstack_gate_env_override) }}"
  register: devstack-gate
  args:
    chdir: "{{ workspace }}"
  command: "./safe-devstack-vm-gate-wrap.sh"
