---
- name: Release the claimed baremetal resource
  command: >
    python {{workspace}}/claim_ciresource.py release
    {{ ansible_local.claimed_baremetal.type }}
    /etc/ansible/facts.d/claimed_baremetal.fact
  when: ansible_local.claimed_baremetal is defined
